[package]
name = "Rocket_Pastebin"
version = "0.1.0"
authors = ["zRyder_"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.3"
rand ="0.6"